### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by rillig** [paul-mannino/go-fuzzywuzzy#4]
A [Code Review answer](https://codereview.stackexchange.com/a/236196) shows that go-fuzzywuzzy is much slower than necessary. The suggestions from there should probably be incorporated into the code.

**Comment by paul-mannino** [comment]
Thanks for the report. As the stackoverflow commenter wryly pointed out, I was/am a python dev writing pygo rather than a go dev writing go. This was my first and last big piece of code, so unfortunately my understanding of go isn't much deeper than it was several years ago. I imagine when I wrote this code I was assuming repeated compilations of an identical regex expression would be cached like they are in other languages, but clearly that is not true :(. Based on how performance compares with the python code after the fix, there probably aren't many order of magnitude performance fixes left in the codebase (but probably plenty of more marginal performance improvements that can be made). I'll profile the code when I get a chance to see if there are any other hotspots I might be missing. Contributions are welcome, so if you're interested, I'd love for someone else to take a closer look as well.
